remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true


sidebar:
  - Label: Equipment
    children:
      - EquipmentStructure
  - Label: Service
    children:
      - ServiceActions
