remote_theme: zendesk/jekyll-theme-zendesk-garden@main

search_enabled: true

title: "Dysel Help"
Description: "Help and documentation for Dysel BC."

sidebar:
  - label: Equipment
    children:
      - EquipmentStructure
  - label: Service
    children:
      - ServiceActions
